spring.application.name=springboot-security-app
server.port=8080

# Google OAuth2 Configuration

spring.security.oauth2.client.registration.google.client-id=<<CLIENT_ID>>
spring.security.oauth2.client.registration.google.client-secret=<<CLIENT_SECRET>>
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# Optional (Spring provides defaults)

# spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
# spring.security.oauth2.client.provider.google.user-name-attribute=sub

# 1 Auth code request
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth

# 2 Token request
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token

# 3 profile request
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo

